### ISSUE TITLE
500 in Admin when Clicking Sales > Payment Options

### ISSUE THREAD

**Issue by shadowcomm** [jslingerland/BluePay_Payment_M2#1]
Hi, I installed everything per your instructions, but when I log into Admin then go to system>config>sales>payment methods I get a 500 error. Evertyhing else seems to be fine. Any thoughts on what might be the issue? 

Thank you! Ben

**Comment by jslingerland** [comment]
Hey Ben,

do you see any entries in your Magento logs (system or exception) for this?

**Comment by shadowcomm** [comment]
Justin,
Thanks for the reply. No, oddly there weren't any errors showing up in either of those logs. I checked the error log as well and nothing. I was going to try to install it again today and will send screenshots. Let me know if you have any other suggestions. 
Thank you,
Ben

**Comment by jslingerland** [comment]
It could be a file permissions issue. Can you verify that your web server has sufficient read/write for the newly installed files?

**Comment by shadowcomm** [comment]
that was my though too, but I couldn't tell from looking where the new extension was being installed and it wasn't in the docs. are you able to tell me where it's being installed?

**Comment by jslingerland** [comment]
All the files get installed into the vendor/bluepay directory

**Comment by shadowcomm** [comment]
Looks like that direcory and everything under it is 775 -http://prntscr.com/fujl73

the vendor folder itself is 755

**Comment by shadowcomm** [comment]
Exception log - http://prntscr.com/fujmec
System log - http://prntscr.com/fujmna
Error log - http://prntscr.com/fujmx8

**Comment by jslingerland** [comment]
Does anything in those logs correlate to the exact time that you hit the Payment Methods page?

**Comment by shadowcomm** [comment]
This is a dev site, so I hit the page and took snaps of the logs right away.

**Comment by jslingerland** [comment]
There's nothing in the Magento exception and system logs that I see that pertains to the BluePay extension. The only thing that's popping out at me is the php memory limit that I see in the error log. Were you getting that before installing the BluePay extension?

**Comment by shadowcomm** [comment]
Yes, the memory was there before. I've increased the memory_limit but that did not seem to fix the issue. I am not able to find any BluePay specific errors either. Very bizarre.

**Comment by jslingerland** [comment]
What version of M2 are you using? I can see if I'm able to replicate this using the same version.

**Comment by shadowcomm** [comment]
Thanks, currently on 2.1.2. 

I have also asked my hosting provider for help with this error. I've increased the memory_limit and still get it. "PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 1318912 bytes) in /home/qualitytablegame/public_$"

**Comment by shadowcomm** [comment]
Hey Justin, my hosting guys just got back to me and fixed the issue. Evidently there was a file named .user.ini in the www directory which was setting the php values instead of in the php.ini. He increased the value from there and the plugin works like a charm. Thank you for your help!
